import type { Metadata } from "next";
import { Providers } from "@/provider/provider";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import LayoutProvider from "@/provider/layout-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "E-Vote",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
